/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LanguageLanguageIdRouteImport } from './routes/language.$languageId'
import { Route as EditLanguageIdRouteImport } from './routes/edit.$languageId'
import { Route as PlayLanguageIdDeckIdRouteImport } from './routes/play.$languageId.$deckId'
import { Route as LeaderboardLanguageIdDeckIdRouteImport } from './routes/leaderboard.$languageId.$deckId'
import { Route as DeckLanguageIdDeckIdRouteImport } from './routes/deck.$languageId.$deckId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageLanguageIdRoute = LanguageLanguageIdRouteImport.update({
  id: '/language/$languageId',
  path: '/language/$languageId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditLanguageIdRoute = EditLanguageIdRouteImport.update({
  id: '/edit/$languageId',
  path: '/edit/$languageId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLanguageIdDeckIdRoute = PlayLanguageIdDeckIdRouteImport.update({
  id: '/play/$languageId/$deckId',
  path: '/play/$languageId/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardLanguageIdDeckIdRoute =
  LeaderboardLanguageIdDeckIdRouteImport.update({
    id: '/leaderboard/$languageId/$deckId',
    path: '/leaderboard/$languageId/$deckId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeckLanguageIdDeckIdRoute = DeckLanguageIdDeckIdRouteImport.update({
  id: '/deck/$languageId/$deckId',
  path: '/deck/$languageId/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/edit/$languageId': typeof EditLanguageIdRoute
  '/language/$languageId': typeof LanguageLanguageIdRoute
  '/deck/$languageId/$deckId': typeof DeckLanguageIdDeckIdRoute
  '/leaderboard/$languageId/$deckId': typeof LeaderboardLanguageIdDeckIdRoute
  '/play/$languageId/$deckId': typeof PlayLanguageIdDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/edit/$languageId': typeof EditLanguageIdRoute
  '/language/$languageId': typeof LanguageLanguageIdRoute
  '/deck/$languageId/$deckId': typeof DeckLanguageIdDeckIdRoute
  '/leaderboard/$languageId/$deckId': typeof LeaderboardLanguageIdDeckIdRoute
  '/play/$languageId/$deckId': typeof PlayLanguageIdDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/edit/$languageId': typeof EditLanguageIdRoute
  '/language/$languageId': typeof LanguageLanguageIdRoute
  '/deck/$languageId/$deckId': typeof DeckLanguageIdDeckIdRoute
  '/leaderboard/$languageId/$deckId': typeof LeaderboardLanguageIdDeckIdRoute
  '/play/$languageId/$deckId': typeof PlayLanguageIdDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/edit/$languageId'
    | '/language/$languageId'
    | '/deck/$languageId/$deckId'
    | '/leaderboard/$languageId/$deckId'
    | '/play/$languageId/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/edit/$languageId'
    | '/language/$languageId'
    | '/deck/$languageId/$deckId'
    | '/leaderboard/$languageId/$deckId'
    | '/play/$languageId/$deckId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/profile'
    | '/register'
    | '/edit/$languageId'
    | '/language/$languageId'
    | '/deck/$languageId/$deckId'
    | '/leaderboard/$languageId/$deckId'
    | '/play/$languageId/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  EditLanguageIdRoute: typeof EditLanguageIdRoute
  LanguageLanguageIdRoute: typeof LanguageLanguageIdRoute
  DeckLanguageIdDeckIdRoute: typeof DeckLanguageIdDeckIdRoute
  LeaderboardLanguageIdDeckIdRoute: typeof LeaderboardLanguageIdDeckIdRoute
  PlayLanguageIdDeckIdRoute: typeof PlayLanguageIdDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language/$languageId': {
      id: '/language/$languageId'
      path: '/language/$languageId'
      fullPath: '/language/$languageId'
      preLoaderRoute: typeof LanguageLanguageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$languageId': {
      id: '/edit/$languageId'
      path: '/edit/$languageId'
      fullPath: '/edit/$languageId'
      preLoaderRoute: typeof EditLanguageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$languageId/$deckId': {
      id: '/play/$languageId/$deckId'
      path: '/play/$languageId/$deckId'
      fullPath: '/play/$languageId/$deckId'
      preLoaderRoute: typeof PlayLanguageIdDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/$languageId/$deckId': {
      id: '/leaderboard/$languageId/$deckId'
      path: '/leaderboard/$languageId/$deckId'
      fullPath: '/leaderboard/$languageId/$deckId'
      preLoaderRoute: typeof LeaderboardLanguageIdDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$languageId/$deckId': {
      id: '/deck/$languageId/$deckId'
      path: '/deck/$languageId/$deckId'
      fullPath: '/deck/$languageId/$deckId'
      preLoaderRoute: typeof DeckLanguageIdDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  EditLanguageIdRoute: EditLanguageIdRoute,
  LanguageLanguageIdRoute: LanguageLanguageIdRoute,
  DeckLanguageIdDeckIdRoute: DeckLanguageIdDeckIdRoute,
  LeaderboardLanguageIdDeckIdRoute: LeaderboardLanguageIdDeckIdRoute,
  PlayLanguageIdDeckIdRoute: PlayLanguageIdDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
