/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayLanguageIdRouteImport } from './routes/play.$languageId'
import { Route as EditLanguageIdRouteImport } from './routes/edit.$languageId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLanguageIdRoute = PlayLanguageIdRouteImport.update({
  id: '/play/$languageId',
  path: '/play/$languageId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditLanguageIdRoute = EditLanguageIdRouteImport.update({
  id: '/edit/$languageId',
  path: '/edit/$languageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/edit/$languageId': typeof EditLanguageIdRoute
  '/play/$languageId': typeof PlayLanguageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/edit/$languageId': typeof EditLanguageIdRoute
  '/play/$languageId': typeof PlayLanguageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/edit/$languageId': typeof EditLanguageIdRoute
  '/play/$languageId': typeof PlayLanguageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/edit/$languageId'
    | '/play/$languageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/edit/$languageId' | '/play/$languageId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/edit/$languageId'
    | '/play/$languageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  EditLanguageIdRoute: typeof EditLanguageIdRoute
  PlayLanguageIdRoute: typeof PlayLanguageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$languageId': {
      id: '/play/$languageId'
      path: '/play/$languageId'
      fullPath: '/play/$languageId'
      preLoaderRoute: typeof PlayLanguageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$languageId': {
      id: '/edit/$languageId'
      path: '/edit/$languageId'
      fullPath: '/edit/$languageId'
      preLoaderRoute: typeof EditLanguageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  EditLanguageIdRoute: EditLanguageIdRoute,
  PlayLanguageIdRoute: PlayLanguageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
